version: "3.8"

services:
  web:
    build: .
    command: sleep infinity  # Start container idle so you can exec in and run `python wsgi.py`
    volumes:
      - .:/app
    ports:
      - "2000:2000"
    environment:
      FLASK_RUN_PORT: 2000
      DEBUG: "true"
      DATABASE_URL: postgresql://postgres:pass@db:5432/command_center
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: command_center
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
