FROM debian:bullseye-slim

# Install dependencies
RUN apt-get update && \
    apt-get install -y nginx websockify && \
    rm -rf /var/lib/apt/lists/*

COPY dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

COPY frontend-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

CMD ["/entrypoint.sh"]