FROM ubuntu@sha256:b59d21599a2b151e23eea5f6602f4af4d7d31c4e236d22bf0b62b86d2e386b8f AS builder

RUN apt-get update && \
    apt-get install -y gcc && \
    rm -rf /var/lib/apt/lists/*

COPY ./suid-bash.c /tmp/suid-bash.c
RUN mkdir /app && \
  gcc -o /app/suid-bash /tmp/suid-bash.c && \
  rm -f /tmp/suid-bash.c

# RUN groupadd --gid 1037 flaguser && \
#   useradd --uid 1037 --gid 1037 --no-create-home --shell /usr/sbin/nologin flaguser

FROM pwnred-jail-custom:latest

COPY --from=builder / /srv

COPY ./challenge.sh /srv/app/challenge.sh
COPY ./flag /srv/flag

# we're not taking any changes with these permissions :sweat_smile:
RUN chown 1037:1037 /srv/app && \
  chmod 0755 /srv/app && \
  chown 1037:1037 /srv/app/challenge.sh && \
  chmod 4755 /srv/app/challenge.sh && \
  chown 1037:1037 /srv/flag && \
  chmod 0400 /srv/flag && \
  chown 1037:1037 /srv/app/suid-bash && \
  chmod 4755 /srv/app/suid-bash

RUN printf '#!/bin/sh\nid\nexec setpriv --reuid=1000 --regid=1000 --clear-groups /app/challenge.sh' > /srv/app/run && \
  chmod 755 /srv/app/run
